### PR TITLE
Milestone1

### PR DESCRIPTION
**Pull request by miftah1991**
Setup And Mobile Version Skeleton -Milestone 1 
I received the comments from my code reviewer and mistakenly closed the first pull request and now I realized that I was not supposed to close the pull request, in this pull request I made the below changes.

- Changed the color of the menu icon to white as per Figma standard
- managed the space  between header and content section
- removed extra space in my all files

### CODE REVIEW

**Review by aliabbani — COMMENTED** [review]
Hi @miftah1991 ✋ , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, However:
- [ ] Your pull request should have a descriptive title explaining what changes are inside. 
- [ ] Your pull request should have a short summary describing the introduced changes in more detail.
Please add a descriptive title and short summary to your pull request 😊 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by miftah1991** [comment]
@aliabbani Sorry for the inconvenience,
I have made the bellow changes in my project.
Changed the color of the menu icon to white as Figma design
manage the space between header and content section

**Review by ReshyResh — APPROVED** [review]
# Hi @miftah1991 , 

### Good job implementing the requested changes from the reviewer in the PR #4 .
### This is one of your first projects and we know mistakes happen. The PR should be merged and closed only once a project has been approved by a code reviewer, but I think you got that already! Good luck with your next milestones!

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by aliabbani** [comment]
> @aliabbani Sorry for the inconvenience, I have made the bellow changes in my project. Changed the color of the menu icon to white as Figma design manage the space between header and content section

Do not worry at all. Good job implementing the changes. Keep it up 🥇

**Pull request merged**
